language: python
python:
- '3.6'
services: docker
git:
  depth: false
install: make docker-login build-docker
stages:
- name: publish-docker
jobs:
  include:
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
env:
  global:
  - secure: pg9ur28z4Zw9c5dyXiDrsB+6I5LMmgAFinNZR5w2EorFmvW3fh9XY76VfI7I6S8LeOyQltJKrD56kUjL2oZ80N4N1k6IzG9mFlVORXzRU9Vz6vNlWbxXZXq7/T3qIHdSL/X84nru0yvATQCvrIcjVv4FsiRoMZCX4bHrjpbxQ6o9klMFqabH8J8fHxPHaR6XKpNRsliEDfUiWfYZmooWITsAZwxr0kashAYoShDve1QBYW+D6e3CFsvFnfT4T5TGjoHkchYQTfgGVMwuPtR+PBoMwfj+TGALO1pwK2a3oNMPooeKzltlidUdJG3DS0JIzI5zI+HCjlLFDjw2DRe4O/JNfjHe6mVqppN0Fug1oabDGUq/rT9GjrLtCSSlx4kaVd3AKxavX6mvxp33+NnwFl+t7qfS05YPwUY73lmiIogXL/vAF7DDrU3lUJlrBGce9saGXUJBNkFVjWGj3MKS3Hp0tCpFVQiiio7tqbW6narySAATKdWK7CJfZAqbtzV6eHVXYA1wUfhdXw/Q5qlo+VVOLvVJM5zPtBZ8HYkP1UmxNea/3bx7e7Xgkf7cXQb/FgKK4ApEwBFn59dFw07qNb4SQOT4X2i9MPRxS8rfLX6v2gw4kBx7WjHdY9Z8iltWJcRpP81kxXg5NcfZSeaTzvk8VinLQwxRsEoiFMryDLc=
  - secure: r5kAYBQq7TL1sGWQnWIa6shIgnT367Mc+jxuPYBlBreiqRZZbArfxlbuuU4t2Uup38YhxpVNkBaVdUpIAjoqTIBppqymUyL0ZGFicNK8U9iaLFLttPisQ4iBdgvxDqYmsq2vbpbGlIR0BOZKXuhodelUr3sButj3e/QohGv0kzcPNFn48LkupSrCtnUOZ2D0ybiSFfLXDFbmLJ14QhNLqJafRZiXQAwOkwL4KYcFVcAYk8OpJY4UHMcctu8MZ/JkwO09rc0mCZVpjOjY1bgg9p1fpP6rZ2124Gv9aoEzglXcpqhfpwHBvOpqmQPGnXFhXPqerxcbIHK2uI5rvtEc+qPJAoUkXPFt1Z0VTkUn/kc4PyCgEDTVTXSN9Sz+sWa0Q55PESh2xv1iyZ2ZEGA5eXIjOEIwZr/tg8l9BJRyxyaqZ6AXAjQo5I1QVEvgq0s6Hou+0o4YCGNO7Dy9IK5SpkFvFlMp5rJpSFVT80/9Mboh8Ze6PRd3X/nSqh+CEx9c1Szpu/SEeY3XmxiDqXIgF68tZXw/ggSBBetWG4o05l75G2EI0DCf786dvZjkDcx+M4LDwo8WpOOQaz51Cvd1XFY0v0YLPbsONQ2sj0cBSwx1KA652igAlZLEZQvbE7LffgJSHXZKGI7sT0l0TLI9ixBuZTzTTKBjrpjz33PKTRg=
